import {
  PhoneIncoming,
  PhoneOutgoing,
  FolderTree,
  Menu,
  PhoneForwarded,
  Hash,
  Grid3X3,
  Voicemail,
  Users,
  PhoneOff,
  ShieldCheck,
  ListOrdered,
  CornerDownRight,
  Slash,
  ToggleLeft,
  Sliders,
  Shuffle,
  GitFork,
  Globe,
  ArrowRight,
  Filter,
  Printer,
  Mic,
  Clock,
  User,
  ExternalLink,
  CheckCircle2,
  XCircle,
  Ban,
  Mail,
  CheckSquare,
  Activity,
  UserCheck,
  PhoneCall,
  MailCheck,
  HelpCircle,
} from "lucide-react";
import type { NodeKind } from "@/schema";

const ICON_MAP: Record<NodeKind, React.ComponentType<{ size?: number; className?: string }>> = {
  incoming_call: PhoneIncoming,
  outgoing_call: PhoneOutgoing,
  menu_root: FolderTree,
  menu_custom: Menu,
  action_transfer: PhoneForwarded,
  action_prompt_extension: Hash,
  action_dial_direct: Grid3X3,
  action_voicemail: Voicemail,
  action_dial_by_name: Users,
  action_disconnect: PhoneOff,
  action_disa: ShieldCheck,
  action_queue: ListOrdered,
  action_goto_menu: CornerDownRight,
  action_nop: Slash,
  answering_mode_ext: ToggleLeft,
  answering_mode_aa: Sliders,
  forward_follow_me: Shuffle,
  forward_advanced: GitFork,
  forward_sip_uri: Globe,
  forward_simple: ArrowRight,
  screening_rule: Filter,
  voicemail: Voicemail,
  fax_mailbox: Printer,
  call_recording: Mic,
  cond_time: Clock,
  cond_caller: UserCheck,
  cond_callee: CheckSquare,
  cond_mode: Activity,
  target_extension: User,
  target_hunt_group_ref: Users,
  target_external: ExternalLink,
  target_sip_uri: Mail,
  term_answered: PhoneCall,
  term_voicemail_left: MailCheck,
  term_forwarded_answered: PhoneForwarded,
  term_forwarded_unanswered: PhoneOff,
  term_rejected: Ban,
  term_dropped: XCircle,
};

export function getNodeIcon(kind: NodeKind): React.ComponentType<{ size?: number; className?: string }> {
  return ICON_MAP[kind] || HelpCircle;
}
