import { z } from "zod";
import { PositionSchema } from "./primitives";
import {
  ActionDialByNameDataSchema,
  ActionDialDirectDataSchema,
  ActionDisaDataSchema,
  ActionDisconnectDataSchema,
  ActionGotoMenuDataSchema,
  ActionPromptExtensionDataSchema,
  ActionQueueDataSchema,
  ActionTransferDataSchema,
  ActionTransferE164DataSchema,
  ActionVoicemailDataSchema,
  AnsweringModeAaDataSchema,
  AnsweringModeExtDataSchema,
  CallRecordingDataSchema,
  CondCalleeDataSchema,
  CondCallerDataSchema,
  CondModeDataSchema,
  CondTimeDataSchema,
  FaxMailboxDataSchema,
  ForwardAdvancedDataSchema,
  ForwardFollowMeDataSchema,
  ForwardSimpleDataSchema,
  ForwardSipUriDataSchema,
  IncomingCallDataSchema,
  MenuCustomDataSchema,
  MenuRootDataSchema,
  OutgoingCallDataSchema,
  ScreeningRuleDataSchema,
  TargetExtensionDataSchema,
  TargetExternalDataSchema,
  TargetHuntGroupRefDataSchema,
  TargetSipUriDataSchema,
  TerminalDataSchema,
  VoicemailDataSchema,
} from "./nodeData";

export const NODE_KINDS = [
  "incoming_call",
  "outgoing_call",
  "menu_root",
  "menu_custom",
  "action_transfer",
  "action_transfer_e164",
  "action_prompt_extension",
  "action_dial_direct",
  "action_voicemail",
  "action_dial_by_name",
  "action_disconnect",
  "action_disa",
  "action_queue",
  "action_goto_menu",
  "answering_mode_ext",
  "answering_mode_aa",
  "forward_follow_me",
  "forward_advanced",
  "forward_sip_uri",
  "forward_simple",
  "screening_rule",
  "voicemail",
  "fax_mailbox",
  "call_recording",
  "cond_time",
  "cond_caller",
  "cond_callee",
  "cond_mode",
  "target_extension",
  "target_hunt_group_ref",
  "target_external",
  "target_sip_uri",
  "term_answered",
  "term_voicemail_left",
  "term_forwarded_answered",
  "term_forwarded_unanswered",
  "term_rejected",
  "term_dropped",
] as const;
export type NodeKind = (typeof NODE_KINDS)[number];

const base = <K extends NodeKind, D extends z.ZodTypeAny>(kind: K, data: D) =>
  z.object({
    id: z.string().min(1),
    type: z.literal(kind),
    position: PositionSchema,
    data,
  });

export const FlowNodeSchema = z.discriminatedUnion("type", [
  base("incoming_call", IncomingCallDataSchema),
  base("outgoing_call", OutgoingCallDataSchema),
  base("menu_root", MenuRootDataSchema),
  base("menu_custom", MenuCustomDataSchema),
  base("action_transfer", ActionTransferDataSchema),
  base("action_transfer_e164", ActionTransferE164DataSchema),
  base("action_prompt_extension", ActionPromptExtensionDataSchema),
  base("action_dial_direct", ActionDialDirectDataSchema),
  base("action_voicemail", ActionVoicemailDataSchema),
  base("action_dial_by_name", ActionDialByNameDataSchema),
  base("action_disconnect", ActionDisconnectDataSchema),
  base("action_disa", ActionDisaDataSchema),
  base("action_queue", ActionQueueDataSchema),
  base("action_goto_menu", ActionGotoMenuDataSchema),
  base("answering_mode_ext", AnsweringModeExtDataSchema),
  base("answering_mode_aa", AnsweringModeAaDataSchema),
  base("forward_follow_me", ForwardFollowMeDataSchema),
  base("forward_advanced", ForwardAdvancedDataSchema),
  base("forward_sip_uri", ForwardSipUriDataSchema),
  base("forward_simple", ForwardSimpleDataSchema),
  base("screening_rule", ScreeningRuleDataSchema),
  base("voicemail", VoicemailDataSchema),
  base("fax_mailbox", FaxMailboxDataSchema),
  base("call_recording", CallRecordingDataSchema),
  base("cond_time", CondTimeDataSchema),
  base("cond_caller", CondCallerDataSchema),
  base("cond_callee", CondCalleeDataSchema),
  base("cond_mode", CondModeDataSchema),
  base("target_extension", TargetExtensionDataSchema),
  base("target_hunt_group_ref", TargetHuntGroupRefDataSchema),
  base("target_external", TargetExternalDataSchema),
  base("target_sip_uri", TargetSipUriDataSchema),
  base("term_answered", TerminalDataSchema),
  base("term_voicemail_left", TerminalDataSchema),
  base("term_forwarded_answered", TerminalDataSchema),
  base("term_forwarded_unanswered", TerminalDataSchema),
  base("term_rejected", TerminalDataSchema),
  base("term_dropped", TerminalDataSchema),
]);
export type FlowNode = z.infer<typeof FlowNodeSchema>;

export type FlowNodeData = FlowNode["data"];

export type NodeOf<K extends NodeKind> = Extract<FlowNode, { type: K }>;
